name: PR Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build-check:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify build
        run: npm run package

      - name: Check if package succeeds
        run: |
          if (Test-Path -Path "out\dxvk-version-mananger-win32-x64") {
            Write-Host "Build successful!"
            exit 0
          } else {
            Write-Host "Build failed!"
            exit 1
          }
        shell: pwsh 